# Generated by Django 3.2.11 on 2022-11-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ski', models.CharField(max_length=255)),
                ('size_ski', models.PositiveIntegerField()),
                ('number_ski', models.PositiveIntegerField()),
                ('size_boots', models.PositiveIntegerField()),
                ('number_boots', models.PositiveIntegerField()),
            ],
        ),
    ]
