# Generated by Django 3.2.12 on 2022-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_app', '0003_auto_20221114_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boot_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boots_size', models.PositiveIntegerField()),
                ('boots_count', models.PositiveIntegerField()),
                ('boots_rent_cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resort_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=255)),
                ('resort_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Ski_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ski_size', models.PositiveIntegerField()),
                ('ski_count', models.PositiveIntegerField()),
                ('ski_rent_cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsc_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('Econom', 'Econom'), ('Business', 'Business')], default='Econom', max_length=20)),
                ('cost_subscr', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SeasonTicket',
        ),
        migrations.DeleteModel(
            name='Uniforms',
        ),
    ]
