# Generated by Django 3.2.12 on 2022-11-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_app', '0004_auto_20221115_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot_directory',
            name='resort_boot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boot', to='Rent_app.resort_directory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ski_directory',
            name='resort_ski',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ski', to='Rent_app.resort_directory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsc_directory',
            name='resort_subsc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsc', to='Rent_app.resort_directory'),
            preserve_default=False,
        ),
    ]
